import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Get Started | Harmey",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        {children}
    </>
  );
}
